apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.team }}
  namespace: taas
spec:
  description: "Project for {{ .Values.team }}"
  sourceRepos:
    - {{ .Values.repo }}
    - {{ .Values.chartsRepo }}
  destinations:
    - namespace: "taas-{{ .Values.team }}-*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
  namespaceResourceWhitelist:
    - group: ""
      kind: ResourceQuota
    - group: ""
      kind: LimitRange
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: ServiceAccount
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
    - group: rbac.authorization.k8s.io
      kind: Role
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: monitoring.coreos.com
      kind: ServiceMonitor
    - group: monitoring.coreos.com
      kind: PrometheusRule
    - group: monitoring.coreos.com
      kind: AlertmanagerConfig
    - group: postgres-operator.crunchydata.com
      kind: PostgresCluster
    - group: batch
      kind: Job
